// 拡張フレーズデータ - 各カテゴリー30個以上に拡充
const EXPANDED_PHRASE_DATA = {
  greetings: {
    '4-6': [
      // 既存の16個
      { english: 'Hello!', japanese: 'こんにちは！', situation: '友達に会ったとき' },
      { english: 'Good morning!', japanese: 'おはよう！', situation: '朝のあいさつ' },
      { english: 'Thank you!', japanese: 'ありがとう！', situation: 'お礼を言うとき' },
      { english: 'Bye bye!', japanese: 'バイバイ！', situation: 'さよならのあいさつ' },
      { english: 'Please!', japanese: 'おねがい！', situation: 'お願いするとき' },
      { english: 'Good night!', japanese: 'おやすみ！', situation: '寝る前のあいさつ' },
      { english: 'Sorry!', japanese: 'ごめんなさい！', situation: '謝るとき' },
      { english: 'Hi there!', japanese: 'やあ！', situation: 'カジュアルなあいさつ' },
      { english: 'Welcome!', japanese: 'ようこそ！', situation: 'お迎えするとき' },
      { english: 'Good afternoon!', japanese: 'こんにちは！', situation: '午後のあいさつ' },
      { english: 'See you!', japanese: 'またね！', situation: 'カジュアルな別れ' },
      { english: 'How are you?', japanese: 'げんき？', situation: '調子を聞く' },
      { english: "I'm fine!", japanese: 'げんきだよ！', situation: '元気な返事' },
      { english: 'Good job!', japanese: 'よくできたね！', situation: '褒めるとき' },
      { english: 'Have fun!', japanese: '楽しんでね！', situation: '遊びに行く時' },
      { english: 'Be careful!', japanese: '気をつけて！', situation: '注意する時' },
      // 追加14個
      { english: 'Hello everyone!', japanese: 'みんな、こんにちは！', situation: 'みんなに挨拶' },
      { english: 'Nice day!', japanese: 'いい天気だね！', situation: '天気の話' },
      { english: "You're welcome!", japanese: 'どういたしまして！', situation: 'お礼の返事' },
      { english: 'Excuse me!', japanese: 'すみません！', situation: '声をかける時' },
      { english: 'Happy birthday!', japanese: 'お誕生日おめでとう！', situation: '誕生日祝い' },
      { english: 'Merry Christmas!', japanese: 'メリークリスマス！', situation: 'クリスマス挨拶' },
      { english: 'Happy New Year!', japanese: 'あけましておめでとう！', situation: '新年の挨拶' },
      { english: 'Good luck!', japanese: 'がんばって！', situation: '応援' },
      { english: 'See you soon!', japanese: 'またすぐ会おうね！', situation: 'すぐ会う約束' },
      { english: 'Take care!', japanese: '元気でね！', situation: '心配の気持ち' },
      { english: 'Well done!', japanese: 'よくできました！', situation: '成果を褒める' },
      { english: 'Hurry up!', japanese: '急いで！', situation: '急かす時' },
      { english: 'Wait for me!', japanese: '待って！', situation: '待ってもらう時' },
      { english: "Let's go!", japanese: '行こう！', situation: '出発する時' },
    ],
    '7-9': [
      // 既存の16個
      { english: 'How are you?', japanese: '元気ですか？', situation: '相手の様子を聞く' },
      { english: 'Nice to meet you.', japanese: 'はじめまして。', situation: '初対面のあいさつ' },
      { english: 'See you later!', japanese: 'またね！', situation: '別れのあいさつ' },
      { english: 'Excuse me.', japanese: 'すみません。', situation: '声をかけるとき' },
      { english: "You're welcome.", japanese: 'どういたしまして。', situation: 'お礼への返事' },
      { english: 'Good to see you!', japanese: '会えて嬉しいです！', situation: '再会のあいさつ' },
      { english: "How's it going?", japanese: '調子はどう？', situation: 'カジュアルな様子聞き' },
      { english: 'Have a good day!', japanese: '良い一日を！', situation: '別れ際の励まし' },
      { english: 'See you tomorrow!', japanese: 'また明日！', situation: '翌日会う約束' },
      { english: 'Take care!', japanese: '気をつけて！', situation: '心配の気持ち' },
      { english: "What's up?", japanese: 'どうしたの？', situation: '様子を聞く' },
      { english: 'Long time no see!', japanese: 'ひさしぶり！', situation: '久々の再会' },
      { english: 'How was your weekend?', japanese: '週末はどうだった？', situation: '月曜の会話' },
      { english: "That's great!", japanese: 'それはすごい！', situation: '相手を褒める' },
      { english: 'Good luck!', japanese: 'がんばって！', situation: '応援する時' },
      { english: 'Congratulations!', japanese: 'おめでとう！', situation: 'お祝い' },
      // 追加14個
      { english: "How's your day?", japanese: '今日はどう？', situation: '日常の様子' },
      { english: 'Welcome back!', japanese: 'おかえり！', situation: '帰宅時の挨拶' },
      { english: 'Have a nice weekend!', japanese: '良い週末を！', situation: '金曜の挨拶' },
      { english: 'Good luck on the test!', japanese: 'テスト頑張って！', situation: '試験応援' },
      { english: 'Happy holidays!', japanese: '良い休日を！', situation: '休日の挨拶' },
      { english: 'Stay safe!', japanese: '安全にね！', situation: '安全を願う' },
      { english: 'Enjoy your vacation!', japanese: '休暇を楽しんで！', situation: '休暇前の挨拶' },
      {
        english: 'Welcome to our class!',
        japanese: '私たちのクラスへようこそ！',
        situation: '新入生歓迎',
      },
      { english: 'How was school?', japanese: '学校はどうだった？', situation: '放課後の会話' },
      { english: 'See you next week!', japanese: '来週会おう！', situation: '週末の別れ' },
      { english: 'Have a great time!', japanese: '楽しい時間を！', situation: '楽しみを祈る' },
      {
        english: 'Thanks for coming!',
        japanese: '来てくれてありがとう！',
        situation: '訪問への感謝',
      },
      {
        english: "It's good to be back!",
        japanese: '戻ってこれてよかった！',
        situation: '復帰の挨拶',
      },
      { english: 'Enjoy your meal!', japanese: '食事を楽しんで！', situation: '食事前の挨拶' },
    ],
    '10-12': [
      // 既存の16個
      {
        english: 'How have you been?',
        japanese: 'お元気でしたか？',
        situation: '久しぶりに会ったとき',
      },
      { english: 'Long time no see.', japanese: 'お久しぶりです。', situation: '久しぶりの再会' },
      { english: 'Have a nice day!', japanese: '良い一日を！', situation: '別れ際の言葉' },
      { english: 'Take care.', japanese: 'お気をつけて。', situation: '心配するとき' },
      { english: 'Best wishes.', japanese: '幸運を祈ります。', situation: '応援するとき' },
      { english: "It's been a while.", japanese: 'しばらくぶりです。', situation: '久々の再会' },
      { english: 'Good luck with that!', japanese: '頑張ってください！', situation: '応援の言葉' },
      { english: 'I appreciate it.', japanese: '感謝します。', situation: '感謝を伝える' },
      { english: 'My pleasure.', japanese: 'どういたしまして。', situation: '丁寧なお礼の返事' },
      { english: 'Have a great weekend!', japanese: '良い週末を！', situation: '週末前のあいさつ' },
      { english: 'Welcome back!', japanese: 'おかえりなさい！', situation: '帰ってきた時' },
      {
        english: 'Hope to see you soon.',
        japanese: 'また近いうちに会えることを願っています。',
        situation: '別れの挨拶',
      },
      {
        english: 'Have a safe trip!',
        japanese: '気をつけて旅行してください！',
        situation: '旅立ちの挨拶',
      },
      {
        english: "It's a pleasure to meet you.",
        japanese: 'お会いできて嬉しいです。',
        situation: '初対面',
      },
      { english: "How's everything?", japanese: '調子はどうですか？', situation: '近況を聞く' },
      { english: 'Keep in touch!', japanese: '連絡を取り合いましょう！', situation: '関係継続' },
      // 追加14個
      {
        english: "It's been too long!",
        japanese: '本当に久しぶりですね！',
        situation: '長期間会わなかった時',
      },
      { english: 'All the best!', japanese: 'ご多幸を祈ります！', situation: '幸せを祈る' },
      {
        english: 'Looking forward to it!',
        japanese: '楽しみにしています！',
        situation: '期待を表す',
      },
      {
        english: 'Thanks for your time.',
        japanese: 'お時間をいただきありがとうございます。',
        situation: '時間への感謝',
      },
      {
        english: 'Have a productive day!',
        japanese: '実りある一日を！',
        situation: '仕事・勉強応援',
      },
      {
        english: 'Enjoy the rest of your day!',
        japanese: '残りの一日を楽しんで！',
        situation: '午後の別れ',
      },
      {
        english: 'It was nice talking to you.',
        japanese: 'お話できてよかったです。',
        situation: '会話後の挨拶',
      },
      {
        english: 'Hope you feel better soon.',
        japanese: '早く良くなることを願っています。',
        situation: '体調を気遣う',
      },
      {
        english: 'Wishing you success!',
        japanese: '成功を祈っています！',
        situation: '成功を願う',
      },
      { english: 'Stay positive!', japanese: '前向きでいてください！', situation: '励ます' },
      {
        english: 'Thanks for everything!',
        japanese: 'いろいろありがとう！',
        situation: '全般的な感謝',
      },
      { english: 'Until next time!', japanese: 'また次回まで！', situation: '次回を期待' },
      { english: 'Safe travels!', japanese: '安全な旅を！', situation: '旅の安全を願う' },
      {
        english: 'Keep up the good work!',
        japanese: 'その調子で頑張って！',
        situation: '継続的な応援',
      },
    ],
  },
  school: {
    '4-6': [
      // 既存の10個
      {
        english: 'May I go to the bathroom?',
        japanese: 'トイレに行ってもいいですか？',
        situation: 'トイレに行きたいとき',
      },
      { english: "I don't understand.", japanese: 'わかりません。', situation: '理解できないとき' },
      {
        english: 'Can you help me?',
        japanese: '手伝ってもらえますか？',
        situation: '助けが必要なとき',
      },
      { english: 'I finished!', japanese: 'できました！', situation: '課題が終わったとき' },
      { english: "Let's play together!", japanese: '一緒に遊ぼう！', situation: '友達を誘うとき' },
      {
        english: 'May I drink water?',
        japanese: '水を飲んでもいいですか？',
        situation: '水を飲みたいとき',
      },
      {
        english: 'I need a pencil.',
        japanese: '鉛筆が必要です。',
        situation: '文房具が必要なとき',
      },
      { english: 'Can I sit here?', japanese: 'ここに座ってもいい？', situation: '席について聞く' },
      { english: 'I like this book!', japanese: 'この本が好き！', situation: '本の感想' },
      { english: "It's my turn!", japanese: '私の番だよ！', situation: '順番を主張' },
      // 追加20個
      {
        english: 'Can I go to the nurse?',
        japanese: '保健室に行ってもいい？',
        situation: '体調不良時',
      },
      { english: 'I forgot my book.', japanese: '本を忘れました。', situation: '忘れ物' },
      { english: 'This is hard.', japanese: 'これは難しい。', situation: '困難を表現' },
      { english: 'This is easy!', japanese: 'これは簡単！', situation: '簡単さを表現' },
      {
        english: 'Can you read this?',
        japanese: 'これを読んでくれる？',
        situation: '読み聞かせ依頼',
      },
      { english: 'I know the answer!', japanese: '答えがわかる！', situation: '回答意欲' },
      { english: 'Can I try?', japanese: 'やってみてもいい？', situation: '挑戦希望' },
      { english: 'I need help.', japanese: '助けが必要です。', situation: '援助要請' },
      { english: 'Look at my work!', japanese: '私の作品を見て！', situation: '作品紹介' },
      { english: 'Can we play outside?', japanese: '外で遊んでもいい？', situation: '外遊び希望' },
      { english: "I'm ready!", japanese: '準備できた！', situation: '準備完了' },
      { english: 'Line up, please!', japanese: '並んでください！', situation: '整列指示' },
      { english: "It's snack time!", japanese: 'おやつの時間だ！', situation: 'おやつ時間' },
      { english: 'Clean up time!', japanese: '片付けの時間！', situation: '片付け' },
      { english: 'Story time!', japanese: 'お話の時間！', situation: '読み聞かせ' },
      { english: 'I lost my eraser.', japanese: '消しゴムをなくした。', situation: '紛失報告' },
      { english: 'Can I borrow this?', japanese: 'これを借りてもいい？', situation: '貸借依頼' },
      { english: 'Thank you, teacher!', japanese: '先生、ありがとう！', situation: '教師への感謝' },
      { english: 'I did it!', japanese: 'できた！', situation: '達成感' },
      { english: "Let's share!", japanese: '分け合おう！', situation: '共有提案' },
    ],
    '7-9': [
      // 既存の10個
      {
        english: 'May I borrow your pencil?',
        japanese: '鉛筆を借りてもいいですか？',
        situation: '物を借りるとき',
      },
      {
        english: 'What page are we on?',
        japanese: '何ページですか？',
        situation: 'ページを確認するとき',
      },
      {
        english: 'I forgot my homework.',
        japanese: '宿題を忘れました。',
        situation: '忘れ物をしたとき',
      },
      {
        english: 'Can you repeat that?',
        japanese: 'もう一度言ってください。',
        situation: '聞き返すとき',
      },
      {
        english: "That's a good idea!",
        japanese: 'それはいいアイデアです！',
        situation: '賛成するとき',
      },
      {
        english: 'When is the test?',
        japanese: 'テストはいつですか？',
        situation: 'テスト日程確認',
      },
      {
        english: 'I need help with this problem.',
        japanese: 'この問題で助けが必要です。',
        situation: '問題解決を求める',
      },
      {
        english: 'Can I join your group?',
        japanese: 'あなたのグループに入ってもいい？',
        situation: 'グループ参加希望',
      },
      {
        english: "I'll share my notes.",
        japanese: '私のノートを共有します。',
        situation: '協力を申し出る',
      },
      { english: "What's for homework?", japanese: '宿題は何ですか？', situation: '宿題内容確認' },
      // 追加20個
      { english: 'Can we work together?', japanese: '一緒に作業できる？', situation: '協力提案' },
      { english: 'I have a question.', japanese: '質問があります。', situation: '質問がある時' },
      { english: 'Is this correct?', japanese: 'これで正しいですか？', situation: '確認' },
      { english: 'I need more time.', japanese: 'もっと時間が必要です。', situation: '時間延長' },
      { english: 'Can I go first?', japanese: '最初にやってもいい？', situation: '順番希望' },
      { english: "Let's study together.", japanese: '一緒に勉強しよう。', situation: '勉強誘い' },
      { english: 'I understand now.', japanese: '今わかりました。', situation: '理解表明' },
      {
        english: 'Can you explain again?',
        japanese: 'もう一度説明してくれる？',
        situation: '再説明依頼',
      },
      { english: 'I agree with you.', japanese: 'あなたに賛成です。', situation: '同意' },
      {
        english: 'I have a different answer.',
        japanese: '違う答えがあります。',
        situation: '異なる意見',
      },
      {
        english: "Let's check our answers.",
        japanese: '答えを確認しよう。',
        situation: '答え合わせ',
      },
      {
        english: 'Can I use the computer?',
        japanese: 'コンピューターを使ってもいい？',
        situation: '機器使用',
      },
      { english: "Where's the library?", japanese: '図書館はどこ？', situation: '場所確認' },
      { english: 'I finished early.', japanese: '早く終わりました。', situation: '早期完了' },
      {
        english: 'Can I help others?',
        japanese: '他の人を手伝ってもいい？',
        situation: '手伝い申し出',
      },
      {
        english: 'What should I do next?',
        japanese: '次は何をすればいい？',
        situation: '次の指示',
      },
      {
        english: 'I like this subject.',
        japanese: 'この教科が好きです。',
        situation: '教科の好み',
      },
      {
        english: 'Can we have more time?',
        japanese: 'もっと時間をもらえる？',
        situation: '時間延長要請',
      },
      { english: "I'll do my best!", japanese: 'ベストを尽くします！', situation: '意欲表明' },
      {
        english: 'Thanks for helping me.',
        japanese: '手伝ってくれてありがとう。',
        situation: '手伝いへの感謝',
      },
    ],
    '10-12': [
      // 既存の10個
      {
        english: 'Could you explain it again?',
        japanese: 'もう一度説明してもらえますか？',
        situation: '再説明を求めるとき',
      },
      { english: 'I have a question.', japanese: '質問があります。', situation: '質問したいとき' },
      {
        english: 'May I work with a partner?',
        japanese: 'パートナーと一緒に作業してもいいですか？',
        situation: '協力したいとき',
      },
      {
        english: 'I need more time.',
        japanese: 'もっと時間が必要です。',
        situation: '時間が足りないとき',
      },
      {
        english: 'I disagree because...',
        japanese: '私は反対です。なぜなら...',
        situation: '意見を述べるとき',
      },
      {
        english: 'Could we discuss this further?',
        japanese: 'これについてもっと議論できますか？',
        situation: '深い議論を求める',
      },
      {
        english: "I'd like to present my findings.",
        japanese: '私の発見を発表したいです。',
        situation: '発表希望',
      },
      {
        english: "What's the deadline for this?",
        japanese: 'これの締切はいつですか？',
        situation: '締切確認',
      },
      {
        english: 'Can I use the computer?',
        japanese: 'コンピューターを使ってもいいですか？',
        situation: '機器使用許可',
      },
      {
        english: "I think there's another solution.",
        japanese: '別の解決策があると思います。',
        situation: '代替案提示',
      },
      // 追加20個
      {
        english: 'May I share my opinion?',
        japanese: '意見を述べてもいいですか？',
        situation: '発言許可',
      },
      {
        english: 'Could you clarify the requirements?',
        japanese: '要件を明確にしてもらえますか？',
        situation: '要件確認',
      },
      {
        english: "I'd like to add to that point.",
        japanese: 'その点に付け加えたいです。',
        situation: '追加発言',
      },
      {
        english: 'What resources are available?',
        japanese: 'どんな資料が利用できますか？',
        situation: '資料確認',
      },
      {
        english: 'Can we form study groups?',
        japanese: '勉強グループを作ってもいいですか？',
        situation: 'グループ形成',
      },
      {
        english: 'I need clarification on this topic.',
        japanese: 'このトピックの説明が必要です。',
        situation: '説明要求',
      },
      {
        english: 'How will this be graded?',
        japanese: 'これはどう採点されますか？',
        situation: '評価基準',
      },
      {
        english: 'Can I submit this electronically?',
        japanese: '電子的に提出してもいいですか？',
        situation: '提出方法',
      },
      {
        english: "I'd appreciate your feedback.",
        japanese: 'フィードバックをいただければ幸いです。',
        situation: 'FB要請',
      },
      {
        english: 'Could we review the main points?',
        japanese: '要点を復習できますか？',
        situation: '復習要請',
      },
      {
        english: "I'm interested in this topic.",
        japanese: 'このトピックに興味があります。',
        situation: '興味表明',
      },
      {
        english: 'Can I do extra credit work?',
        japanese: '追加課題をやってもいいですか？',
        situation: '追加課題',
      },
      {
        english: "What's the learning objective?",
        japanese: '学習目標は何ですか？',
        situation: '目標確認',
      },
      {
        english: "I'd like to explore this further.",
        japanese: 'これをさらに探求したいです。',
        situation: '深堀り希望',
      },
      {
        english: 'Can we have a study session?',
        japanese: '勉強会を開けますか？',
        situation: '勉強会提案',
      },
      {
        english: 'I appreciate the explanation.',
        japanese: '説明に感謝します。',
        situation: '説明への感謝',
      },
      {
        english: 'Could you recommend additional reading?',
        japanese: '追加の読み物を推薦してもらえますか？',
        situation: '追加資料',
      },
      {
        english: 'I understand the concept now.',
        japanese: '今、概念を理解しました。',
        situation: '理解確認',
      },
      {
        english: 'May I revise my work?',
        japanese: '作業を修正してもいいですか？',
        situation: '修正希望',
      },
      {
        english: 'Thank you for your guidance.',
        japanese: 'ご指導ありがとうございます。',
        situation: '指導への感謝',
      },
    ],
  },
};

// エクスポート
if (typeof module !== 'undefined' && module.exports) {
  module.exports = EXPANDED_PHRASE_DATA;
}
